spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/users
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: users_scheme
    generate-ddl: true
    show-sql: true